django/erad/urls.py
from django.urls import path

from erad import views

app_name = "erad"
urlpatterns = [
    path("list", views.EradListView.as_view(), name="list"),
]

django/grant/urls.py
from django.urls import path

from grant import views

app_name = "grant"
urlpatterns = [
    path("list", views.GrantListView.as_view(), name="list"),
    path("create", views.GrantCreateView.as_view(), name="create"),
    path("<int:pk>/update", views.GrantUpdateView.as_view(), name="update"),
    path("<int:pk>/delete", views.GrantDeleteView.as_view(), name="delete"),
    path("export", views.GrantExportView.as_view(), name="export"),
]

django/shikin/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from . import settings

urlpatterns = [
    path("", TemplateView.as_view(template_name="frontpage.html"), name="frontpage"),
    path("erad/", include("erad.urls")),
    path("grant/", include("grant.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

django/erad/models.py
from django.db import models


class Erad(models.Model):
    erad_key = models.CharField(
        "e-Rad公募ID", max_length=7, unique=True, blank=True, null=True)
    erad_url = models.URLField("e-Rad公募情報URL", blank=True, null=True)
    url = models.URLField("URL", blank=True, null=True)
    publishing_date = models.DateField("公開日")
    funding_agency = models.CharField("配分機関", max_length=200)
    call_for_applications = models.CharField("公募名", max_length=200)
    application_unit = models.CharField("応募単位", max_length=200)
    approved_institution = models.CharField("機関承認の有無", max_length=200)
    opening_date = models.DateField("受付開始日")
    closing_date = models.DateField("受付終了日")

    def __str__(self):
        return self.funding_agency + "／" + self.call_for_applications

django/grant/models.py
from django.db import models


class Grant(models.Model):
    ARRANGE = (("0", ""), ("1", "有"), ("2", "無"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    accepted_at = models.DateField("受付日")
    zaidanmei = models.CharField("財団等の名称", max_length=200)
    koubomei = models.CharField("公募名", max_length=200)
    url = models.URLField("財団等のURL", blank=True)
    torimatome = models.CharField("本部による取りまとめ", max_length=1, choices=ARRANGE)
    bikou = models.TextField("備考", blank=True)

    def __str__(self):
        return self.zaidanmei + self.koubomei

    class Meta:
        verbose_name = "研究資金公募情報"
        verbose_name_plural = "研究資金公募情報"

django/erad/forms.py
from django import forms


FA = (
    ("", "選択なし"),
    ("国立研究開発法人日本医療研究開発機構", "国立研究開発法人日本医療研究開発機構(AMED)"),
    ("国立研究開発法人情報通信研究機構", "国立研究開発法人情報通信研究機構(NICT)"),
    ("国立研究開発法人科学技術振興機構", "国立研究開発法人科学技術振興機構(JST)"),
    ("独立行政法人日本学術振興会", "独立行政法人日本学術振興会(JSPS)"),
    ("国立研究開発法人医薬基盤・健康・栄養研究所", "国立研究開発法人医薬基盤・健康・栄養研究所(NIBIOHN)"),
    ("国立研究開発法人農業・食品産業技術総合研究機構", "国立研究開発法人農業・食品産業技術総合研究機構(NARO)"),
    ("国立研究開発法人新エネルギー・産業技術総合開発機構", "国立研究開発法人新エネルギー・産業技術総合開発機構(NEDO)"),
    ("独立行政法人環境再生保全機構", "独立行政法人環境再生保全機構"),
    ("内閣府", "内閣府"),
    ("総務省", "総務省"),
    ("消防庁", "消防庁"),
    ("文部科学省", "文部科学省"),
    ("厚生労働省", "厚生労働省"),
    ("農林水産省", "農林水産省"),
    ("農林水産省農林水産政策研究所", "農林水産省農林水産政策研究所"),
    ("経済産業省", "経済産業省"),
    ("国土交通省", "国土交通省"),
    ("国土技術政策総合研究所", "国土技術政策総合研究所"),
    ("環境省", "環境省"),
    ("原子力規制庁", "原子力規制庁"),
    ("防衛省", "防衛省"),
)


class EradSearchForm(forms.Form):
    fa = forms.ChoiceField(label="配分機関", choices=FA, required=False)

django/grant/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from django import forms
from django.urls import reverse

from grant.models import Grant


class GrantForm(forms.ModelForm):
    class Meta:
        model = Grant
        fields = ["accepted_at", "zaidanmei",
                  "koubomei", "url", "torimatome", "bikou"]
        widgets = {"accepted_at": DatePickerInput(format='%Y-%m-%d')}

    def __init__(self, *args, **kwargs):
        super(GrantForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit("", "保存"))


class GrantSearchForm(forms.Form):
    q = forms.CharField(label="助成財団等の名称、公募名", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('q'),
        )
        self.helper.form_method = "GET"
        self.helper.form_action = reverse("grant:list")
        self.helper.add_input(Submit("", "絞り込み"))

django/erad/views.py
from django.views.generic import ListView

from .forms import EradSearchForm
from .models import Erad
import datetime


class EradListView(ListView):
    paginate_by = 1000
    template_name = "erad/erad_list.html"

    def get_queryset(self):
        form = self.form = EradSearchForm(self.request.GET or None)
        # 受付終了日前の案件を抽出する
        queryset = Erad.objects.filter(closing_date__gte=datetime.date.today())
        # 配分機関のフィルタ条件を設定する
        if form.is_valid():
            fa = form.cleaned_data.get("fa")
            if fa:
                queryset = queryset.filter(funding_agency__contains=fa)
        queryset = queryset.order_by("publishing_date").reverse()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = self.form
        return context

django/grant/views.py
import csv
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.db.models import Q

from grant.forms import GrantForm, GrantSearchForm
from grant.models import Grant


class GrantListView(ListView):
    paginate_by = 100
    queryset = Grant.objects.all()
    ordering = ["-accepted_at", "-updated_at"]

    def get_queryset(self):
        queryset = super().get_queryset()
        form = self.form = GrantSearchForm(self.request.GET or None)
        if form.is_valid():
            q = form.cleaned_data.get("q")
            if q:
                queryset = queryset.filter(
                    Q(zaidanmei__contains=q) | Q(koubomei__contains=q))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = self.form
        return context


class GrantCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Grant
    form_class = GrantForm
    success_message = "保存しました。"
    success_url = reverse_lazy("grant:list")


class GrantUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Grant
    form_class = GrantForm
    success_message = "保存しました。"
    success_url = reverse_lazy("grant:list")


class GrantDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Grant
    success_message = "削除しました。"
    success_url = reverse_lazy("grant:list")


class GrantExportView(View):
    def get(self, request):
        response = HttpResponse(content_type="text/csv; charset=cp932")
        now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        filename = "zaidan_export_" + now
        response["Content-Disposition"] = "attachment; filename=" + \
            filename + ".csv"
        writer = csv.writer(response)
        writer.writerow(["整理番号", "更新日", "財団等の名称", "公募名",
                         "公募URL", "本部での取りまとめの有無", "備考"])
        grant_list = Grant.objects.all().order_by("accepted_at").reverse()
        for grant in grant_list:
            row = [
                grant.id,
                grant.accepted_at,
                grant.zaidanmei.encode("cp932", "ignore").decode("cp932"),
                grant.koubomei.encode("cp932", "ignore").decode("cp932"),
                grant.url,
                grant.torimatome,
                grant.bikou.encode("cp932", "ignore").decode("cp932"),
            ]
            writer.writerow(row)
        return response

django/erad/templates/erad/erad_list.html
{% extends "_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1 class="h2 my-3">政府系の競争的研究資金公募情報</h1>
        </div>
    </div>

    <form method="GET" action="" name="filter_form">
        <div class="form-group border rounded p-3 mt-4">
            <h2 class="h6">絞り込み</h2>
            <div class="row">
                <div class="col-md-6">
                    {{ search_form.fa | as_crispy_field }}
                </div>
                <div class="col-md-6">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-search"></i>
                検索
            </button>
        </div>
    </form>
    {% if object_list %}
    <div class="alert alert-primary my-4">
        検索結果：<span class="h2">{{ paginator.count | intcomma }}</span> 件
    </div>
    <p>公開日または受付終了日のヘッダ行をクリックすることで、ソート可能です。</p>
    <table id="sort-table" class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th width=10%>公開日</th>
                <th width=50%>配分機関、公募名</th>
                <th width=10%>応募単位</th>
                <th width=10%>機関承認</th>
                <th width=10%>受付終了日</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.publishing_date }}</td>
                <td>
                    <div><small class="text-muted">{{ object.funding_agency }}</small></div>
                    <div>
                        {{ object.call_for_applications }}
                    </div>
                    <div>
                        <small><a href="{{ object.erad_url|default:'#' }}" target="_blank"
                                rel="noopener noreferrer">{{ object.erad_url|default:'' }}</a></small>
                    </div>
                    <div>
                        <small><a href="{{ object.url|default:'#' }}" target="_blank"
                                rel="noopener noreferrer">{{ object.url|default:'' }}</a></small>
                    </div>
                </td>
                <td>{{ object.application_unit }}</td>
                <td>{{ object.approved_institution }}</td>
                <td>{{ object.closing_date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="my-5">見つかりませんでした。</p>
    {% endif %}

</div>

{% endblock %}

django/grant/templates/grant/grant_list.html
{% extends "_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
<div class="container-fluid">
    <h1 class="h3 my-5">新潟大学に郵便やメールで通知のあった民間助成財団等の公募情報</h1>

    <div class="row">
        <div class="col-md-4">
            <div class="card card-info">
                <div class="card-body">
                    <h2 class="h6">絞り込み</h2>
                    {% crispy search_form　search_form.helper %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-info">
                <div class="card-body">
                    <h2 class="h6">全データの取得</h2>
                    <a class="btn btn-outline-primary my-3 mr-3" href="{% url 'grant:export' %}">CSV形式でダウンロード</a>
                </div>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class="col-md-4">
            <div class="card card-info">
                <div class="card-body">
                    <h2 class="h6">公募情報の新規登録</h2>
                    <a class="btn btn-outline-primary my-3 mr-3" href="{% url 'grant:create' %}">新規登録</a>
                </div>
            </div>
        </div>
        {% endif %}

    </div>



    {% if grant_list %}
    <div class="alert alert-primary my-5">
        検索結果：<span class="h3">{{ paginator.count | intcomma }}</span> 件
        （{{ page_obj.paginator.num_pages }} ページのうち {{ page_obj.number }} ページ目を表示）

    </div>
    {% include "grant/_pagination.html" %}

    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th width=10%>更新日</th>
                <th width=50%>助成財団等の名称、公募名</th>
                <th width=10%>研究推進課による取りまとめ</th>
                <th width=20%>備考</th>
                {% if request.user.is_authenticated %}
                <th width=10%></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for grant in grant_list %}
            <tr>
                <td>
                    {{ grant.accepted_at | date:"Y-m-d" }}
                </td>
                <td>
                    <div><small class="text-muted">{{ grant.zaidanmei }}</small></div>
                    <div>{{ grant.koubomei }}</div>
                    {% if grant.url %}
                    <div>
                        <small><a href="{{ grant.url }}" target="_blank" rel="noopener noreferrer">{{ grant.url }}</a></small>
                    </div>
                    {% endif %}
                </td>
                <td>
                    <div>{{ grant.get_torimatome_display }}</div>
                </td>
                <td>
                    <div>{{ grant.bikou|linebreaksbr }}</div>
                </td>
                {% if request.user.is_authenticated %}
                <td>
                    <a class="btn btn-sm btn-outline-primary" href="{% url 'grant:update' grant.pk %}">編集</a>
                    <a class="btn btn-sm btn-outline-warning" href="{% url 'grant:delete' grant.pk %}">削除</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include "grant/_pagination.html" %}

    {% else %}
    <p class="my-5">見つかりませんでした。</p>
    {% endif %}
</div>

{% endblock %}

django/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>新潟大学 研究資金公募情報</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <!-- tablesorter -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
    <!-- <style>
        #fav-table th {
            background-color: pink;
        }

        .tablesorter-headerUnSorted {
            background-image: url('img/sort.png');
            background-repeat: no-repeat;
            background-position: center right;
        }

        .tablesorter-headerAsc {
            background-image: url('img/sort_a.png');
            background-repeat: no-repeat;
            background-position: center right;
            border-bottom: #000 2px solid;
        }

        .tablesorter-headerDesc {
            background-image: url('img/sort_d.png');
            background-repeat: no-repeat;
            background-position: center right;
            border-bottom: #000 2px solid;
        }
    </style> -->
    <script>
        $(document).ready(function () {
            $('#sort-table').tablesorter({
                headers: {
                    1: { sorter: false },
                    2: { sorter: false },
                    3: { sorter: false },
                }
            });
        });
    </script>
    <!-- tablesorter end -->
    {{ form.media }}
    <link rel="stylesheet" href="{% static 'css/shikin.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'frontpage' %}">新潟大学 研究資金公募情報</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false" aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'grant:list' %}">民間助成財団等の公募情報</a>
                </li>
                <li class="nav-item">
                    <!--<a class="nav-link" href="{% url 'erad:list' %}">政府系の競争的研究資金公募情報</a>-->
                    <a class="nav-link" href="https://www.e-rad.go.jp/offer_list.html" target="_blank">政府系の競争的研究資金公募情報</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    Login ID : <strong>{{ request.user }}</strong> - <a href="/accounts/logout/">ログアウトする</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% else %}
    <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    <footer class="footer py-3 bg-light">
        <div class="container text-muted">
            <div class="row my-4">
                <div class="col-md-12">
                    <h4><a href="{% url 'frontpage' %}">新潟大学 研究資金公募情報</a></h4>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-md-12">
                    <div><a href="{% url 'grant:list' %}">民間助成財団等の公募情報</a></div>
                    <!--<div><a href="{% url 'erad:list' %}">政府系の競争的研究資金公募情報</a></div>-->
                    <div><a href="https://www.e-rad.go.jp/offer_list.html" target="_blank">政府系の競争的研究資金公募情報</a></div>
                </div>

            </div>
            <hr>
            <div class="row my-4">
                <div class="col-md-12">
                    <h5>掲載内容・手続きについて</h5>
                </div>
            </div>
            {% include "_toiawase.html" %}
            <hr>
            <div class="row my-4">
                <div class="col-md-12">
                    <h5>システムの不具合について</h5>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-md-12">
                    <dl>
                        <dt>研究企画室 URA</dt>
                        <dd>内線 7569</dd>
                        <dd><a href="mailto:rao2@adm.niigata-u.ac.jp">rao2@adm.niigata-u.ac.jp</a></dd>
                    </dl>
                </div>
            </div>
            <hr>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#fav-table').tablesorter();
        });
    </script>



</body>

</html>

django/templates/frontpage.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row my-5">
        <div class="col-md-6 pr-5">
            <h2 class="h4">民間助成財団等の公募情報</h2>
            <p> 各種助成金等に応募する場合は、所属部局の事務部担当係に応募書類の写しを提出してください。</p>
            <p> 学長印や部局長推薦等が必要な公募の場合は、手続きに日数が必要です。</p>
            <div class="card my-3 bg-light shadow" id="frontpage_card1">
                <a href="{% url 'grant:list' %}" class="text-decoration-none">
                    <div class="card-body">
                        <h1 class="card-title h4">一覧を見る</h1>
                        <p class="card-text">新潟大学に郵便やメールで通知のあったものを表示します</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-6 pl-5">
            <h2 class="h4">政府系の競争的研究資金公募情報</h2>
            <p> 国・政府系機関の公募で、<a href="https://www.e-rad.go.jp/" target="_blank"> 
                府省共通研究開発システム（e-Rad）</a>を利用するものについては、
                申請書類の機関承認が必要な場合があります。機関承認が必要な公募の場合は、<strong>e-Radの申請期限（受付終了日）の 5
                    営業日前までに（学内締切）</strong>、研究推進課研究資金係 kenkyushikin@adm.niigata-u.ac.jp 内線5457 に申請書を提出してください。</p>
            <p>JSPSの電子申請システム経由で応募する科学研究費助成事業等については、別途部局等を通じて通知されます。</p>
            <div class="card my-3 bg-light shadow" id="frontpage_card1">
                <!--<a href="{% url 'erad:list' %}" class="text-decoration-none">-->
                <a href="https://www.e-rad.go.jp/offer_list.html" target="_blank" class="text-decoration-none">
                    <div class="card-body ">
                        <h1 class="card-title h4">一覧を見る</h1>
                        <!--<p class="card-text">e-Radに掲載されている公募情報です</p>-->
                        <p class="card-text">e-Rad公募一覧へのリンク</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <hr>
    <hr>
    <div class="row">
        <div class="col">
            <div class="alert alert-info py-5" role="alert">
                以下は参考情報です
            </div>
        </div>
    </div>
    <div class="row my-4">
        <div class="col-md-12">
            <h2 class="h4">公募情報（新潟大学内）</h2>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-md-4">
            <h3 class="h6">医学部医学科 学内向け情報</h3>
            <ul>
                <li><a href="https://www.med.niigata-u.ac.jp/contents/campus/staff/other/joseikinn/index.html"
                        target="_blank">研究助成　公募一覧</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
        </div>
    </div>
    <div class="row my-4">
        <div class="col-md-12">
            <h2 class="h4">公募情報（一次情報）</h2>
            <p>資金配分機関による公募情報のページを紹介します。</p>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-md-4">
            <h3 class="h6">府省共通研究開発管理システム e-Rad</h3>
            <ul>
                <li><!--<a href="https://www.e-rad.go.jp/erad/portal/jigyolist/present/present?locale=ja"
                        target="_blank">--><a href="https://www.e-rad.go.jp/offer_list.html" target="_blank">公募一覧</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3 class="h6">AMED - 日本医療研究開発機構</h3>
            <ul>
                <li><a href="https://www.amed.go.jp/search.php" target="_blank">公募情報検索</a></li>
                <li><a href="https://www.amed.go.jp/koubo/yokoku_index.html" target="_blank">公募予告一覧</a></li>
                <li><a href="https://www.amed.go.jp/koubo/koubo_index.html" target="_blank">公募情報一覧</a></li>
                <li><a href="https://www.amed.go.jp/pr/mailmagazine.html" target="_blank">AMEDメール配信サービス</a></li>
            </ul>
            <h3 class="h6 mt-5">JSPS - 日本学術振興会</h3>
            <ul>
                <li><a href="https://www.jsps.go.jp/info/index1.html" target="_blank">公募情報一覧</a></li>
                <li><a href="https://www.jsps.go.jp/j-mailmagazine/subscription.html" target="_blank">JSPS
                        Monthly</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3 class="h6">JST - 科学技術振興機構</h3>
            <ul>
                <li><a href="https://www.jst.go.jp/bosyu/bosyu.html" target="_blank">公募情報一覧</a></li>
                <li><a href="https://www.jst.go.jp/melmaga.html" target="_blank">JSTが発行するメールマガジン</a></li>
            </ul>
            <h3 class="h6 mt-5">NEDO - 新エネルギー・産業技術総合開発機構</h3>
            <ul>
                <li><a href="https://www.nedo.go.jp/search/?type=koubo" target="_blank">公募情報一覧</a></li>
                <li><a href="https://www.nedo.go.jp/nedomail/index.html" target="_blank">NEDOメール配信サービス</a></li>
            </ul>
        </div>
    </div>
    <div class="row my-4">
        <div class="col-md-12">
            <h2 class="h4">公募情報（二次情報）</h2>
            <p>公募情報が掲載されているサイトを紹介します。</p>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-md-4">
            <h3 class="h6">公益財団法人 助成財団センター</h3>
            <ul>
                <li><a href="http://www.jfc.or.jp/grant-search/c_search.php5" target="_blank">助成プログラム検索</a></li>
                <li><a href="http://www.jfc.or.jp/grant-search/z_search.php5" target="_blank">団体名による検索</a></li>
                <li><a href="http://www.jfc.or.jp/grant-search/ap_search.php5" target="_blank">採択課題からの検索</a></li>
                <li><a href="http://www.jfc.or.jp/grant-search/news/" target="_blank">助成金募集ニュース</a></li>
                <li><a href="http://www.jfc.or.jp/z-link/link/" target="_blank">助成財団リンク集</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3 class="h6">JST - 科学技術振興機構 サイエンスポータル</h3>
            <ul>
                <li><!--<a href="https://scienceportal.jst.go.jp/funding/application/application.php"
                        target="_blank">--><a href="https://scienceportal.jst.go.jp/funding/" target="_blank">ファンド（研究助成）</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3 class="h6">株式会社ジー・サーチ</h3>
            <ul>
                <li><!-- <a href="https://www.colabory.com/grants/" target="_blank">-->
                    <a href="https://beats.colabory.com/" target="_blank">COLABORY／Beats!</a></li>
            </ul>
            <h3 class="h6 mt-5">株式会社キーエンス</h3>
            <ul>
                <li><a href="https://www.e-grant.jp/" target="_blank">e-GRANT</a></li>
            </ul>
            <h3 class="h6 mt-5">株式会社アイ・スクウェア</h3>
            <ul>
                <li><a href="https://info-innovation.jp/" target="_blank">グラント・スクウェア</a></li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}